# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
    paths:
      - '**'
      - '!README*'
      - '!changelog.txt'

  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build image
        run: |
          echo "PPPOE_USERNAME=123" >> modules/network/.env
          echo "PPPOE_PASSWORD=123" >> modules/network/.env
          echo "LAN_IP=192.168.1.1" >> modules/network/.env
          echo "CLASH_CONFIG_URL=https://gist.github.com/EkkoG/20a52db0169c4a4769689521b1c5500e/raw/cf61a9397d0bdbd5b6bbad8fbb388ec851116470/clash_example.yaml" >> modules/openclash/.env
          echo "MODULES=openclash openclash-as-default -statistics" > .env
          ./run.sh --image=openwrt/imagebuilder:x86-64-23.05.2
      - name: Upload
        id: upload
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          PROFILE: generic.x86_64
        run: |
          # Prepare Release
          pwd
          ls ./ -alh
          tree ./
          ARTIFACTPATH="$(pwd)/image/"
          mkdir -p $ARTIFACTPATH
          cd $ARTIFACTPATH
          # Upload image
          ls bin/targets/x86/64/ -alh
          ls ./ -alh
          cp bin/targets/x86/64/* ./
          git init
          git config user.name "bot"
          git config user.email "bot@github.com"
          git add .
          git commit -m "$PROFILE$(TZ='Asia/Shanghai' date +@%Y%m%d)"
          git push --force --quiet "https://$GITHUB_TOKEN@github.com/fangguangyang/OpenWrt.git" HEAD:image/$PROFILE
      - uses: actions/upload-artifact@main
        with:
          name: image_generic.x86_64
          path: ./image